### PR TITLE
Complete Refactor

### PR DESCRIPTION
**Pull request by TonybynMp4**
*Added Qb-Target compatibility
*Added Locales
*Updated event names to english
*Fixed a bug where the explosion would send the truck flying in a direction
*Fixed police alerts
*Added Config File
*Blocked cops from starting / participating in the mission
*Removed the silence alarm because it's kinda useless (the mission auto restarts) and didn't seem to work properly 
*Removed unnecessary handlers (thanks to #14 and #15 👍🏻  )

Questions (please complete the following information):
- Have you personally loaded this code into an updated qbcore project and checked all it's functionality?
[yes but not without qb-target, should work tho] (Be honest)
- Does your code fit the style guidelines? [yes]
- Does your PR fit the contribution guidelines? [yes]

### CODE REVIEW

**Comment by TonybynMp4** [comment]
That lint thing is pretty neat, should be all good now 👍🏻

**Comment by Howsn** [comment]
Thanks for this update! :D

Quick question, I have modified this to be triggerd with a item instead of npc.
But I have a problem where you gett a new mission after the cooldown timer is finished.
I did not have this problem with the old version, and I cant find where it is..
Everything looks the same.

**Comment by Howsn** [comment]
Thanks for this update :)

There is one problem i'm having, you could try it yourself.
When the reset timer kicks inn and you can rob the truck again the last person who did it gets a "free" mission without talking to the npc.

**Comment by TonybynMp4** [comment]
hhmm that's weird
i'll look into it

**Comment by TonybynMp4** [comment]
> There is one problem i'm having, you could try it yourself. When the reset timer kicks inn and you can rob the truck again the last person who did it gets a "free" mission without talking to the npc.

I can't seem to reproduce this, if you could tell me exactly what to do to reproduce it ? it would really help

**Comment by Howsn** [comment]
> > There is one problem i'm having, you could try it yourself. When the reset timer kicks inn and you can rob the truck again the last person who did it gets a "free" mission without talking to the npc.
> 
> I can't seem to reproduce this, if you could tell me exactly what to do to reproduce it ? it would really help

Yes :)

For testing i set the reset timer to 200. 
After i finish the mission and the 200 reset timer kicks inn I get a new mission for free.
I get a new mail and a new car spawn.

**Comment by TonybynMp4** [comment]
> For testing i set the reset timer to 200. After i finish the mission and the 200 reset timer kicks inn I get a new mission for free. >I get a new mail and a new car spawn.

It doesn't happen to me, maybe try reinstalling the script ?

**Comment by Howsn** [comment]
> 

I think the problem was that I ensured the script withoute relogging xD

**Comment by Howsn** [comment]
> > For testing i set the reset timer to 200. After i finish the mission and the 200 reset timer kicks inn I get a new mission for free. >I get a new mail and a new car spawn.
> 
> It doesn't happen to me, maybe try reinstalling the script ?

Okey, we have tested this alot on the live server now and we have problems with the blip (tracking on the truck) disapears and the robbery get scuffed and you cant rob the truck, the scenario dosent work. You got any clue whats wrong? I had the same problem on the last script aswell.

**Comment by TonybynMp4** [comment]
Idk it disappears when the mission's over that's it 🤔

**Comment by TonybynMp4** [comment]
> the blip (tracking on the truck) disapears and the robbery get scuffed and you cant rob the truck

I'd say maybe you run out of time (reset timer too short) cauz that's the only reason i see for it to reset like this

**Comment by Howsn** [comment]
> 

The timer is 3600, 1 houre. So thats not the problem :)
I will try a fix where the truck dosent spawn before your close to it.

Thanks for the answer! <3

**Comment by TonybynMp4** [comment]
>I will try a fix where the truck dosent spawn before your close to it.

Maybe that'll work but i didn't do it so the truck isn't always at the spawn point, makes it a bit harder / more repeatable

**Comment by FadedRP** [comment]
When target system is activated the ped doesn't spawn and the script doesn't work getting an error code client.lua line 35

**Comment by TonybynMp4** [comment]
> When target system is activated the ped doesn't spawn and the script doesn't work getting an error code client.lua line 35

Could show the error please, i don't have any errors

**Comment by commodore72** [comment]
Howdy, finally you fixed this script so that its actually good, the only thing im having an error with is that people can just keep robbing the back, i just had someone rob take at least 12 bags out the back when my config is at max 3. any fix? id love to keep using your amazing work!

**Comment by TonybynMp4** [comment]
> Howdy, finally you fixed this script so that its actually good, the only thing im having an error with is that people can just keep robbing the back, i just had someone rob take at least 12 bags out the back when my config is at max 3. any fix? id love to keep using your amazing work!

Are you using target ?

**Comment by TonybynMp4** [comment]
> Howdy, finally you fixed this script so that its actually good, the only thing im having an error with is that people can just keep robbing the back, i just had someone rob take at least 12 bags out the back when my config is at max 3. any fix? id love to keep using your amazing work!

Thanks! 
if you have an actual error please show it to me, i tried the robbery multiple times and never had that problem so i can't really help you

**Comment by TonybynMp4** [comment]
@commodore72 i think i found and fixed your problem, try again now :p

**Comment by commodore72** [comment]
> @commodore72 i think i found and fixed your problem, try again now :p


That worked Thank you! amazing job!

**Comment by TonybynMp4** [comment]
@GhzGarage it'd be cool if you could take a look at this PR :p

**Comment by GhzGarage** [comment]
@MatthewRorke

**Comment by MvtiasG** [comment]
@TonybynMp4 . Excuse my ignorance I am trying to get the script to work, but the NPC does not appear, I am checking the code and there is a "leo" job, is that leo ? I am totally lost with that. No one can see the NPC that gives the mission.

**Comment by TonybynMp4** [comment]
@MvtiasG a recent update to the core added the possibility to have job types, so you can check for multiple jobs simply by checking for the type, leo is the type that was added to the police job in that change (so to make it work natively i used that one)
Either your core isn't up to date or there's something wrong i didn't see when i tested it.

**Comment by commodore72** [comment]
> @MvtiasG a recent update to the core added the possibility to have job types, so you can check for multiple jobs simply by checking for the type, leo is the type that was added to the police job in that change (so to make it work natively i used that one) Either your core isn't up to date or there's something wrong i didn't see when i tested it.

so sorry, id assume my core is no longer up to date because when i try to do the mission now (it worked fine before, never had any issues)  it says "required two police" even when two are on and on duty, any idea how to fix and or revert? as updating  my core is not an option at the moment

**Comment by TonybynMp4** [comment]
> so sorry, id assume my core is no longer up to date because when i try to do the mission now (it worked fine before, never had any issues) it says "required two police" even when two are on and on duty, any idea how to fix and or revert? as updating my core is not an option at the moment

i'd guess you can just change back the .type == 'leo' to .name == 'police'

**Comment by jonezkti** [comment]
Instead of using a single line for every one of the possible spawn locations, you could create a table with coords and just pick the one from there with something like
```lua
vehCoords = Config.SpawnPoints[math.random(#Config.SpawnPoints)]
```
Example of the table:
```lua
Config.SpawnPoints = {
	vector3(-1327.479736328, -86.045326232910, 49.31),
	vector3(-2075.888183593, -233.73908996580, 21.10),
	vector3(-972.1781616210, -1530.9045410150, 4.890),
	vector3(798.18426513672, -1799.8173828125, 29.33),
	vector3(1247.0718994141, -344.65634155273, 69.08)
}
```

**Review by sinphoenix — APPROVED** [review]
ive tested and works fine on my end!

**Comment by TonybynMp4** [comment]
^ Updated to use the convars for locales

**Pull request closed without merging**
