### PR TITLE
rework truck robbery

### PR DESCRIPTION
**Pull request by haitham1337**

### CODE REVIEW

**Comment by ZonixZA** [comment]
might be a stupid question but how does one trigger this robbery ? or is it more like you have to find the van roaming?

**Comment by haitham1337** [comment]
yes

**Comment by goncalocarvalho95** [comment]
How do this work?

**Comment by haitham1337** [comment]
Search the streets for the vehicle

**Comment by darknight2590** [comment]
Where do I find the vehicle? I couldn't find it on the street

**Comment by lordfalcon22** [comment]
You may want to change the used item to something else due to security_card_2 is used for bank robbery so it conflicts.

**Comment by BerkieBb** [comment]
Conflicts

**Comment by ItsANoBrainer** [comment]
I am very straightforward, so this is going to be extremely blunt.

This code is actually atrocious. Did you even write this or just copy-paste a bunch of stuff together and call it a resource? There are so many dead, unused functions and variables in this is actually crazy. I couldn't even get past the first few function of this review. You have all the logic for saving PlayerData but never use it. A ridiculous amount of global variables CREATED in functions, but never defined outside the function.

It doesn't seem like you actually understand any of the code you 'use' or have in this resource.

**Review by ItsANoBrainer — COMMENTED** [review]
I am very straightforward, so this is going to be extremely blunt.

This code is actually atrocious. Did you even write this or just copy-paste a bunch of stuff together and call it a resource? There are so many dead, unused functions and variables in this is actually crazy. I couldn't even get past the first few function of this review. You have all the logic for saving PlayerData but never use it. A ridiculous amount of global variables CREATED in functions, but never defined outside the function.

It doesn't seem like you actually understand any of the code you 'use' or have in this resource. I am denying this PR.

**Pull request closed without merging**
